[#34] Replace `removeFirst` with `removeAt`
pacu/zcash-kotlin-payment-uri pull request #35
Opened 2024-10-16 11:44 UTC by HonzaR

- The removal is also moved under the empty collection check to avoid an empty collection removal exception if that case could happen
- Closes #34

2024-10-16 12:43 UTC, pacu approved these changes

2024-10-16 12:52 UTC, pacu requested changes
Thanks for this contribution Honza!

I ran test on this PR and one failed. 

```
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :lib:test

org.zecdev.zip321.ZcashSwiftPaymentUriTests > test that a single payment request is generated FAILED
    io.kotest.assertions.AssertionFailedError at ZcashSwiftPaymentUriTests.kt:41

73 tests completed, 1 failed

```

2024-10-17 06:24 UTC, HonzaR commented
Hi @pacu, I see. Then, the separation of the two commands and having them in similar conditions would work as expected, and the impacted test would pass, too. I pushed it.

2024-10-17 11:42 UTC, pacu approved these changes
utACK

2024-10-17 11:42 UTC, merged